services: 
  postgres:
    image: postgres:latest
    container_name: my_postgres_orders
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - 5433:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data